#!/bin/sh

# Copyright 2015-2018 Joel Allen Luellwitz, Andrew Klapp, and Brittney Scaccia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case "$1" in
    configure)

    # Default Linux user and group information
    BATWATCH_USER='batwatch'
    BATWATCH_USER_COMMENT='Battery Watch Daemon'
    BATWATCH_GROUP='batwatch'
    GPGMAILER_GROUP='gpgmailer'

    # Add the batwatch group
    if ! getent group "$BATWATCH_GROUP" >> /dev/null; then
        echo -n "Adding group $BATWATCH_GROUP..."
        addgroup --quiet --system "$BATWATCH_GROUP" 2> /dev/null
        echo "done"
    fi

    # Add the batwatch user
    if ! getent passwd "$BATWATCH_USER" >> /dev/null; then
        echo -n "Adding system user $BATWATCH_USER..."
        adduser --quiet --system --ingroup "$BATWATCH_GROUP" --no-create-home --disabled-password \
            "$BATWATCH_USER" 2> /dev/null
        echo "done"
    fi

    # Adjust the user regardless of whether this script created the user or not.
    #   (The user might already exist.)
    usermod -c "$BATWATCH_USER_COMMENT" -d "/nonexistent" -g "$BATWATCH_GROUP" \
        -G "$GPGMAILER_GROUP" "$BATWATCH_USER"
    ;;
esac

update-rc.d batwatch defaults || exit 1
invoke-rc.d batwatch start || exit 1
